// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEJZ88YsbVj0ttw7l2d1J5j_QZmeYoVZw',
    appId: '1:807386950190:web:d38cd761bf8361c004cdbf',
    messagingSenderId: '807386950190',
    projectId: 'nemurasa',
    authDomain: 'nemurasa.firebaseapp.com',
    storageBucket: 'nemurasa.firebasestorage.app',
    measurementId: 'G-R4QSBRK3PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3abSklEilLujTqzlpd3BMpz-9DOm9iJQ',
    appId: '1:807386950190:android:b5861f6e6ffff41904cdbf',
    messagingSenderId: '807386950190',
    projectId: 'nemurasa',
    storageBucket: 'nemurasa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg7sCdOYzhjPNKrZI5Lt9sSXiZjSotlTg',
    appId: '1:807386950190:ios:e7da74b63fd3771d04cdbf',
    messagingSenderId: '807386950190',
    projectId: 'nemurasa',
    storageBucket: 'nemurasa.firebasestorage.app',
    androidClientId: '807386950190-d26o36ovnkcgubur8dv2hihm5q2avaoj.apps.googleusercontent.com',
    iosClientId: '807386950190-61p0g7rt21s2akt4v0luob6keub40mv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nemurasa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBg7sCdOYzhjPNKrZI5Lt9sSXiZjSotlTg',
    appId: '1:807386950190:ios:e7da74b63fd3771d04cdbf',
    messagingSenderId: '807386950190',
    projectId: 'nemurasa',
    storageBucket: 'nemurasa.firebasestorage.app',
    androidClientId: '807386950190-d26o36ovnkcgubur8dv2hihm5q2avaoj.apps.googleusercontent.com',
    iosClientId: '807386950190-61p0g7rt21s2akt4v0luob6keub40mv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nemurasa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEJZ88YsbVj0ttw7l2d1J5j_QZmeYoVZw',
    appId: '1:807386950190:web:40d4bfe48729421904cdbf',
    messagingSenderId: '807386950190',
    projectId: 'nemurasa',
    authDomain: 'nemurasa.firebaseapp.com',
    storageBucket: 'nemurasa.firebasestorage.app',
    measurementId: 'G-PDYBXPFN4T',
  );

}